import board

# GPXX
ANALOG_OUTPUT   = board.GP26
ANALOG_SELECT_A = board.GP5
ANALOG_SELECT_B = board.GP4

ARROW_LEFT  = board.GP2
ARROW_DOWN  = board.GP3
ARROW_UP    = board.GP6
ARROW_RIGHT = board.GP7

TRIGGER_LEFT = board.GP8
BUMPER_LEFT  = board.GP9

SELECT = board.GP10
START = board.GP11

TRIGGER_RIGHT = board.GP12
BUMPER_RIGHT  = board.GP13

ACTION_LEFT = board.GP18
ACTION_DOWN = board.GP19
ACTION_UP = board.GP20
ACTION_RIGHT = board.GP21

SWITCHES = [
    (0, ARROW_LEFT),
    (1, ARROW_DOWN),
    (2, ARROW_UP),
    (3, ARROW_RIGHT),

    (4, TRIGGER_LEFT),
    (5, BUMPER_LEFT),

    (6, SELECT),
    (7, START),

    (8, TRIGGER_RIGHT),
    (9, BUMPER_RIGHT),

    (10, ACTION_LEFT),
    (11, ACTION_DOWN),
    (12, ACTION_UP),
    (13, ACTION_RIGHT),
]
